### ISSUE TITLE
F11 not using TCC.args from settings.json

### ISSUE THREAD

**Issue by paccerdk** [nikomedes/vs-tcc#1]
With a settings.json looking like this:
```
{
    "files.associations": {
        "stdio.h": "c",
        "winuser.h": "c"
    },
    "TCC.args": "-lkernel32 -luser32"
}
```

pressing F10 results in the following command being run:
`tcc.exe  "c:\path\main.c" -run  -lkernel32 -luser32`

pressing F11 results in the following command being run:
`tcc.exe  "c:\path\main.c"`

Is this intended behaviour? It seems to me like TCC.args should be used in both cases
Thanks!

**Comment by nikomedes** [comment]
Yes, seems to be missing! Will try to fix it asap.

**Comment by nikomedes** [comment]
Bug is fixed. New Version 1.0.3 is available for download in the marketplace.
