### ISSUE TITLE
New version installer broken

### ISSUE THREAD

**Issue by paccerdk** [nikomedes/vs-tcc#2]
Installing the new version of the plugin and pressing f10 / f11 on a project that worked with the previous version.
With the new version, it results in the error:

'c:\vspath\extensions\nikomedes.vs-tcc-1.0.3\tcc-win32\tcc.exe' is not recognized as an internal or external command, operable program or batch file.

I checked inside the extension folder, and tcc.exe is nowhere to be found.

I've tried a clean install too, which gives same result.

**Comment by nikomedes** [comment]
Missed to include some files. Fixed in Version 1.0.4.
